### PR TITLE
Remove top menu

### PR DESCRIPTION
**Pull request by ChickenNuggers**
Remove the top menu so it looks (almost, if not exactly) like `chromium --app="https://irccloud.com"`.

### CODE REVIEW

**Comment by jwheare** [comment]
Does this remove all the menu items or just move them somewhere else?

**Comment by ChickenNuggers** [comment]
It removes the menu entirely.

**Comment by jwheare** [comment]
Would rather keep it.

**Comment by navidR** [comment]
at least introduce an option for hiding menu bar, it would be much better. (just like what VSCode does have)

**Comment by ChickenNuggers** [comment]
This was discussed and rejected.

**Comment by navidR** [comment]
I think rejection was about removing whole menu, I am proposing introducing new option for toggling menu bar (which almost all of apps does have).Should I create new issue ?

**Pull request closed without merging**
