### PR TITLE
Add RPM target to electron-builder.json

### PR DESCRIPTION
**Pull request by gtirloni**
Relates to irccloud/irccloud-desktop/issues/122

Environment information and build results: [irccloud-desktop-rpm-build-results.txt](https://github.com/irccloud/irccloud-desktop/files/2388895/irccloud-desktop-rpm-build-results.txt)

### CODE REVIEW

**Comment by gtirloni** [comment]
Maybe the build environment is broken?

**Comment by willwh** [comment]
Really would be nice to see this get merged.

**Comment by jdoss** [comment]
Can this get some attention so we can have some nice RPMs to install?

**Comment by jwheare** [comment]
This would need to be integrated into our travis CI job, likely using a docker build. I am not familiar enough with the fedora ecosystem to set this up myself.

**Pull request closed without merging**
