### PR TITLE
Add icon to application window itself

### PR DESCRIPTION
**Pull request by charliewolf**

### CODE REVIEW

**Comment by russss** [comment]
Are you running the app directly from Electron rather than from the built .exe? From the [Electron docs](http://electron.atom.io/docs/v0.37.2/api/browser-window/#new-browserwindowoptions):

> when omitted on Windows the executable’s icon would be used as window icon.

And for me the window has the right icon on Windows.

**Comment by charliewolf** [comment]
I'm using Linux.
 
On Sun, Mar 27, 2016, at 09:30 AM, Russ Garrett wrote:
> Are you running the app directly from Electron rather than from the
> built .exe? From the Electron docs[1]:
>> when omitted on Windows the executable’s icon would be used as
>> window icon.
> And for me the window has the right icon on Windows.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[2]
>
 

Links:

  1. http://electron.atom.io/docs/v0.37.2/api/browser-window/#new-browserwindowoptions
  2. https://github.com/irccloud/irccloud-desktop/pull/23#issuecomment-202072462

**Comment by russss** [comment]
Aha, right. Weird that Electron doesn't do that on Linux.

You've got the same issue here as in #22 where you're hardcoding the path separator, but if you replace it with `path.join` I'll merge this.

**Comment by charliewolf** [comment]
Not that weird when you consider that the ELF format predates the desktop and Linux doesn't have  any way to embed icons in the executable.

**Comment by charliewolf** [comment]
I updated it, though.

**Pull request merged**
